#! /bin/sh

### BEGIN INIT INFO
# Provides: indigopiface
# Required-Start: $network $local_fs
# Should-Start: 
# Required-Stop: 
# Should-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: IndigoDomo-PiFace integration
# Description:    Runs IndigoDomo-PiFace integration daemon
### END INIT INFO


# Instalacion:
# 
# Copiar en /etc/init.d/indigopiface
# chmod u+x /etc/init.d/indigopiface
# sudo update-rc.d -f indigopiface defaults

DESC="IndigoDomo-PiFace integation daemon"
NAME="indigopiface"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

cd /home/pi/indigopiface

case "$1" in
  start)
    #echo "Starting IndigoPiface"
    # Start the daemon 
    python /home/pi/indigopiface/indigopiface.py start
    ;;
  stop)
    #echo "Stopping IndigoPiface"
    # Stop the daemon
    python /home/pi/indigopiface/indigopiface.py stop
    ;;
  restart)
    #echo "Restarting IndigoPiface"
    python /home/pi/indigopiface/indigopiface.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/indigopiface {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
